apiVersion: v2
name: loki-wrapper
description: Wrapper chart to deploy Loki with repo-owned values.
type: application
version: 0.1.0

dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: "5.47.2"
