# Values are passed to the "loki" dependency chart.
loki:
  deploymentMode: SingleBinary

  singleBinary:
    replicas: 1

  read:
    replicas: 0

  write:
    replicas: 0

  backend:
    replicas: 0

  auth_enabled: false

  affinity: {}
  podAntiAffinity: {}

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: filesystem

  persistence:
    enabled: true
    size: 5Gi

  limits_config:
    retention_period: 24h

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  gateway:
    enabled: false

  lokiCanary:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
        enabled: false

  grafanaAgent:
    enabled: false

  grafanaAgentOperator:
    enabled: false
    crds:
      create: false
      enabled: false

  chunksCache:
    enabled: false

  resultsCache:
    enabled: false
