# Values are passed to the "ingress-nginx" dependency chart.
ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
